run:
  tests: true
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  misspell:
    locale: US
  lll:
    line-length: 79
linters:
  enable-all: true
  disable:
    - gochecknoinits

